### ISSUE TITLE
RFE:  how about reading mysql dump files?

### ISSUE THREAD

**Issue by sphakka** [Alexis-benoist/eralchemy#100]
It looks like mysql dump files are not supported:
```bash
$ eralchemy -i file:///schema.sql -o schema.pdf
Traceback (most recent call last):
  File "/home/marcoep/.local/bin/eralchemy", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/marcoep/.local/lib/python3.11/site-packages/eralchemy/main.py", line 31, in cli
    render_er(
  File "/home/marcoep/.local/lib/python3.11/site-packages/eralchemy/main.py", line 231, in render_er
    tables, relationships = all_to_intermediary(input, schema=schema)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcoep/.local/lib/python3.11/site-packages/eralchemy/main.py", line 152, in all_to_intermediary
    raise ValueError(msg)
ValueError: Cannot process filename_or_input str
```
It's the same without the `file:///`.

**Comment by maurerle** [comment]
currently, we only support reading from `*.er` file or from any sqlalchemy compatible database connection string as input.

We could add `*.sql` files as input, though we would need some more information how to parse this.
Currently, this is not planned, but you can give it a try if you want to :)

**Comment by maurerle** [comment]
Handling random files would require to guess (or provide) the input database type as well - this is hard and depends on the dialect.
So one needs to restore a dump/backup first before creating a database diagram from it for now.

Closing this as won't fix.
