### ISSUE TITLE
Installation fails if SQLAlchemy is not installed

### ISSUE THREAD

**Issue by aaron0browne** [Alexis-benoist/eralchemy#15]
Error output is below. I believe this issue is caused because `setup.py` imports `__version__` from the `eralchemy.__init__.py` and that file imports a bunch of other stuff in order to support the `cli` method. I think it could be fixed by moving the `cli` method to the `main.py` file and making the appropriate adjustment to the `entrypoint` value in `setup.py`.

```
Collecting ERAlchemy==1.0.5 (from -r test_requirements.txt (line 3))
  Using cached ERAlchemy-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g6whlgt5/ERAlchemy/setup.py", line 2, in <module>
        from eralchemy import __version__
      File "/tmp/pip-build-g6whlgt5/ERAlchemy/eralchemy/__init__.py", line 2, in <module>
        from eralchemy.main import render_er
      File "/tmp/pip-build-g6whlgt5/ERAlchemy/eralchemy/main.py", line 3, in <module>
        from eralchemy.sqla import metadata_to_intermediary, declarative_to_intermediary, database_to_intermediary
      File "/tmp/pip-build-g6whlgt5/ERAlchemy/eralchemy/sqla.py", line 8, in <module>
        from sqlalchemy.exc import CompileError
    ImportError: No module named 'sqlalchemy'
```

**Comment by aaron0browne** [comment]
The above PR includes the proposed code moves and allows the package to be installed successfully without having SQLAlchemy installed already. Tests passed once I installed `psycopg2` and `flask_sqlalchemy`, except for those that require a database named `test`.
