### ISSUE TITLE
Failure when using on PG with citext extension enabled

### ISSUE THREAD

**Issue by claudyus** [Alexis-benoist/eralchemy#51]
I try to make a DB diagram of a postgresql database using eralchemy version 1.2.7 and I get the following error:

```
/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py:2650: SAWarning: Did not recognize type 'citext' of column 'name'
  (attype, name))
/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py:2650: SAWarning: Did not recognize type 'citext' of column 'email'
  (attype, name))
/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py:2650: SAWarning: Did not recognize type 'citext' of column 'first_name'
  (attype, name))
/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py:2650: SAWarning: Did not recognize type 'citext' of column 'last_name'
  (attype, name))
/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py:2650: SAWarning: Did not recognize type 'citext' of column 'account_number'
  (attype, name))
Traceback (most recent call last):
  File "/home/cmignanti/.envs/labjack/bin/eralchemy", line 11, in <module>
    sys.exit(cli())
  File "/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/eralchemy/main.py", line 38, in cli
    schema=args.s
  File "/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/eralchemy/main.py", line 231, in render_er
    tables, relationships = all_to_intermediary(input, schema=schema)
  File "/home/cmignanti/.envs/labjack/local/lib/python2.7/site-packages/eralchemy/main.py", line 152, in all_to_intermediary
    raise ValueError(msg)
ValueError: Cannot process filename_or_input str
```

I believe this is related to the usage of citext extension in on db table. You can find more info about citext here [1] but I believe that for this project those can be consider text fields.

1. https://www.postgresql.org/docs/current/static/citext.html

**Comment by Alexis-benoist** [comment]
Which command do you type?

2018-03-01 22:25 GMT+01:00 Claudio Mignanti <notifications@github.com>:

**Comment by claudyus** [comment]
The command was simple:
`eralchemy -i postgres://db:dbpassword@172.17.0.1/portal?sslmode=disable -o schema.png`

**Comment by maurerle** [comment]
Using:

```sql
CREATE EXTENSION citext;
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
CREATE TABLE test_er (
	name citext,
	mail citext,
	behavior mood
)
```

I get a working output:

<img width="287" height="158" alt="Image" src="https://github.com/user-attachments/assets/25553847-f8ba-44f4-8445-8a631867af4b" />
